### ISSUE TITLE
Failure to install correctly.

### ISSUE THREAD

**Issue by Sybrand** [bcgov/smk-cli#60]
I tried to use the cli, but get errors on installation:

```
npm install --global @bcgov/smk-cli
npm WARN deprecated text-encoding@0.6.4: no longer maintained
/home/sybrand/.nvm/versions/node/v14.15.1/bin/smk -> /home/sybrand/.nvm/versions/node/v14.15.1/lib/node_modules/@bcgov/smk-cli/index.js
+ @bcgov/smk-cli@1.0.0
added 178 packages from 192 contributors in 6.413s
```

```
smk help
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/sybrand/.nvm/versions/node/v14.15.1/lib/node_modules/@bcgov/smk-cli/node_modules/figlet/fonts/sl script.flf'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Function.figlet.loadFontSync (/home/sybrand/.nvm/versions/node/v14.15.1/lib/node_modules/@bcgov/smk-cli/node_modules/figlet/lib/node-figlet.js:48:23)
    at Function.me.textSync (/home/sybrand/.nvm/versions/node/v14.15.1/lib/node_modules/@bcgov/smk-cli/node_modules/figlet/lib/figlet.js:879:43)
    at Object.<anonymous> (/home/sybrand/.nvm/versions/node/v14.15.1/lib/node_modules/@bcgov/smk-cli/index.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/sybrand/.nvm/versions/node/v14.15.1/lib/node_modules/@bcgov/smk-cli/node_modules/figlet/fonts/sl script.flf'
}
```

**Comment by NicoledeGreef** [comment]
@qqnluaq  - can you please investigate and advise?

**Comment by franTarkenton** [comment]
Just put in this pr: https://github.com/bcgov/smk-cli/pull/64 which should address this issue.  PR is master->master.  Wasn't sure what branch to tie to the PR.  Let me know if it should go to a different branch and I can re-issue it if that would help
