### ISSUE TITLE
MPCM catalog fails to load

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#61]
Open SMK Editor and click through the different type of layers.  When "Manage DataBC Layers" is selected there is a failure.

Possibly related to infrastructure changes relating to apps.gov.bc.ca which is the host for MPCM.

2021-04-21T18:03:46.041Z GET /config
    Reading config from C:\apps\smk-fap-fcb\smk-config.json
2021-04-21T18:03:57.561Z GET /catalog/local
    Reading catalog from C:\apps\smk-fap-fcb\layers\-smk-catalog.json
    Success!
2021-04-21T18:04:05.325Z GET /catalog/wms/https%3A%2F%2Fopenmaps.gov.bc.ca%2Fgeo%2Fpub%2Fwms
    Loading WMS Catalog from https://openmaps.gov.bc.ca/geo/pub/wms?version=1.3.0&service=wms&request=GetCapabilities
    Success!
**2021-04-21T18:04:14.523Z GET /catalog/mpcm
    Loading MPCM Catalog from https://apps.gov.bc.ca/pub/mpcm/services/catalog/PROD
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\ndegreef\AppData\Roaming\npm\node_modules\smk-cli\smk-edit\controllers\catalogs.js:78:29)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)**

**Comment by NicoledeGreef** [comment]
https://github.com/bcgov/smk-cli/pull/62

**Comment by dgboss** [comment]
The problem was trying to make a HTTPS request on port 80 uses the http module. Solution was to use the https module which defaults to port 443.

**Comment by dgboss** [comment]
New package has been published to npm - v1.0.1

**Comment by NicoledeGreef** [comment]
npm install --global @bcgov/smk-cli

v1.0.1 installed
test site created and used SMK Editor to access MPCM layers and add them
